### ISSUE TITLE
Uninstall Mixman DM2 Driver(s)

### ISSUE THREAD

**Issue by stungeye** [arseneyr/mixman-dm2#1]
Hi. I was able to install the v1.1 release of your Mixman DM2 drivers using method 1 of your [provided link](https://www.thewindowsclub.com/disable-driver-signature-enforcement-windows). In other words, I was able to temporarily disable driver signature enforcement and then install. After that I could receive midi signals from a plugged in DM2. 

The problem is that after I boot back into Windows without the driver signature enforcement disabled then none of my USB ports work for anything. My mouse won't work. My printer won't work. The DM2 won't work. Nothing.

All USB devices work again after I use the advanced menu to boot back into Windows with driver signature enforcement disable. 

Is there a way to uninstall your driver(s) so that I don't have to continue to use the advanced boot menu? 

I tried permanently disabling driver signature enforcement using the other methods mention at your [provided link](https://www.thewindowsclub.com/disable-driver-signature-enforcement-windows), but that didn't work.

Any help you could provide would be much appreciated. Thanks.

**Comment by stungeye** [comment]
Hi, it's me again. Immediately after posting my issue I remembered that Windows creates automatic restore points when you install a new driver. This allowed me to perform a system restore to before the DM2 driver(s) were installed. All my USB ports are operational again.

But now I'm torn. I'd really love to be able to revive my DM2 but I don't want to have to constantly boot into a special mode to use my USB ports. Am I out of luck?

**Comment by arseneyr** [comment]
The reason USB is breaking is because this driver package includes a USB bus filter driver to work around buggy firmware in the Mixman device. When driver signature enforcement is enabled, this filter driver fails to load and the entire USB stack doesn't work. I've added an uninstallation script to the release package and updated the readme. Sorry about that.

There's good news and bad news. The bad news is that Windows requires all kernel drivers to be signed by Microsoft to load on a stock Windows install. Certification requires an expensive EV certificate and extensive testing that I'm not willing to go through. 

The good news is that if you're willing to sacrifice Secure Boot on your system, you can enable test signing once and not have to boot into a special mode every time. I've updated the readme to reflect this method. Of course, you lose the the rootkit protections that Secure Boot brings, so I don't recommend doing this on anything critical.

**Comment by stungeye** [comment]
Hi Arseney. Thanks for the explanation and the addition of the uninstall script to the repo.

It's good to know about the buggy device firmware too. I had been trying to get the DM2 to work with its original software using a Windows XP VM, but I wasn't able to get the host OS to passthrough the USB device. The host OS (Windows 10) kept failing to load the device due to an invalid configuration descriptor, which I'm guessing is the firmware issue you are referring to.

Very cool work on this driver by the way. Sounds like it was a bit of a challenge, what with the need for the USB filter, and the driver signing, and the low-level C coding required. Did you already know how to code device drivers before this project? 

Please feel free to close this issue and thank you for your work on this project. 😊
